default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username: postgres
  password: owl123

development:
  <<: *default
  database: Zoomag
  host: localhost


production:
  <<: *default
  database: Zoomag
  host: <%= ENV['DATABASE_URL'] %> # Use your production host or a cloud service URL
  port: 5432
